### ISSUE TITLE
 not able to push

### ISSUE THREAD

**Issue by cfontes** [Goodsmileduck/helm-push-action#1]
I have a java project with a structure like this

```
Root 
  |
  |  --- module
  |           | -- target
  |                    | -- chart 
```

When I run the action from the root directory i get the following error, which from my research is a [helm package issue](https://github.com/helm/helm/issues/1979).

` directory name (chart) and Chart.yaml name (market-query-service) must match`

Any idea on how to workaround it?

My action configs are this

```

    - name: Build with Maven
      run: mvn clean install -Ppublish-container
    - uses: goodsmileduck/helm-push-action@v0.1.1
      env:
        SOURCE_DIR: '****-service/target/chart'
        CHART_FOLDER: '.'
        FORCE: 'True'
        CHARTMUSEUM_URL: 'https://xxxxxx.com/'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
```

I've tried different `SOURCE_DIR` and `CHART_FOLDER` configurations but nothing worked so far.

If I run this command on my local machine instead of GitHub Actions it actually works

```helm push *****-service/target/chart chartmuseum```

from the same directory after the same maven command, which leads me to think the directory structure inside the container used by Github actions can be the cause, but I am not sure yet.

Thanks
