### ISSUE TITLE
fail to push

### ISSUE THREAD

**Issue by denispeyrusaubes** [Goodsmileduck/helm-push-action#24]
I'm using your plugin in order to publish my helm to chart to ChartMuseum

I'e got this problem.

![helm-error](https://user-images.githubusercontent.com/7138984/190932609-9248c739-bfd0-4c03-8af4-b9043d243302.jpg)

It seems that generated chart is not found by the action. 
Something wrong ?

Thanks for your help

**Comment by Goodsmileduck** [comment]
@denispeyrusaubes do you set required params? CHART_FOLDER especially?

**Comment by KrustyHack** [comment]
Ay,

I got same problem : https://github.com/Goodsmileduck/helm-push-action/issues/25

**Comment by Goodsmileduck** [comment]
also check example for action in this repo
https://github.com/Goodsmileduck/helm-push-action/blob/master/.github/workflows/helm3.yml#L37-L45

**Comment by gasparpn** [comment]
@Goodsmileduck I belive https://github.com/Goodsmileduck/helm-push-action/pull/29 solves this one too.

**Comment by yalattas** [comment]
experiencing same issue

## usgae
```
 - name: Upload Charts
        uses: goodsmileduck/helm-push-action@v2
        env:
          CHARTMUSEUM_URL: 'https://charts.company.com'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          FORCE: 'True'
          SOURCE_DIR: '.'
          CHART_FOLDER: charts/ambassador-crd   # this is coming here dynamically, hence I couldn't use SOURCE_DIR and CHART_FOLDER at the same time. Otherwise, I will have to adjust previous steps
```

## error
```
Successfully packaged chart and saved it to: /github/workspace/charts/ambassador-crd/ambassador-crd-v2.0.2-pr-3.tgz
No requirements found in /github/workspace/charts/ambassador-crd/charts.
Error: stat charts/ambassador-crd-*: no such file or directory
Error: plugin "push" exited with error
```
