### ISSUE TITLE
Is '${CHART_FOLDER}-*' a typo ?

### ISSUE THREAD

**Issue by KrustyHack** [Goodsmileduck/helm-push-action#25]
Ay,

Thanks for this Ghitub Action, but I have a question about the last line : https://github.com/Goodsmileduck/helm-push-action/blob/39d65bb6f8cdc3b7b4655a5598ec38da767e788a/entrypoint.sh#L52

Is `${CHART_FOLDER}-*` a typo ?

I got this error on my workflow :

```
  build-helm:
    name: Build Helm
    runs-on: ubuntu-latest

    needs: [xxx]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: goodsmileduck/helm-push-action@v3
        env:
          SOURCE_DIR: '.'
          CHART_FOLDER: 'my/path'
          FORCE: 'True'
          CHARTMUSEUM_URL: '${{ secrets.ORG_CHARTMUSEUM_URL }}'
          CHARTMUSEUM_USER: '${{ secrets.ORG_CHARTMUSEUM_USERNAME }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.ORG_CHARTMUSEUM_PASSWORD }}
```

```
+ helm cm-push 'my/path-*' *** -u *** -p '***' -f
Error: stat my/path-*: no such file or directory
```
